### ISSUE TITLE
Problem of person reid dataset

### ISSUE THREAD

**Issue by woocoder** [SUTDCV/UAV-Human#14]
Hello, I found that the most of the angles are horizontal in the images of person reid in the dataset.
It doesn't look like a drone camera shot.

It is something wrone? Or I download yhe wrong data?

![P000S00G10B10H10UC022000LC021000A000R0_08241716_170_bbx](https://user-images.githubusercontent.com/11451001/175798881-e13e94dc-2418-4979-95ea-b4f2bd89cd0a.jpg)
![P000S01G10B10H50UC022000LC021000A031R0_08251609_138_bbx](https://user-images.githubusercontent.com/11451001/175798885-0a74d9e0-570a-4fe3-a391-ec4afad0a6b5.jpg)
![P014S08G10B30H30UC051000LC021000A110R0_09292142_234_bbx](https://user-images.githubusercontent.com/11451001/175798887-761ce5db-0120-4d10-91c9-208d3e3ff461.jpg)
![P018S00G10B30H30UC022000LC022000A068R0_08261355_066_bbx](https://user-images.githubusercontent.com/11451001/175798888-9ecace20-219f-4803-8751-7aa69eca10a0.jpg)

**Comment by sayano-lee** [comment]
Hi, thanks for your interest in our dataset. To keep safe, our drone is flying further away from people in most cases. And thus at a greater distance, the angles in the captured images look smaller.
