### ISSUE TITLE
where is the "train_test_split.json"  file in the skeleton dataset?

### ISSUE THREAD

**Issue by Kebii** [SUTDCV/UAV-Human#2]
Thank you!

**Comment by sayano-lee** [comment]
Hi, thanks for the attention, the ```train_test_split.json``` will be released together with the dataset, pls wait for the data release. Thanks!

**Comment by Yarloy** [comment]
Can't wait for the release of the dataset! Btw, could you please tell me when the dateset is expected to be released? Thanks a lot!

**Comment by sayano-lee** [comment]
> Can't wait for the release of the dataset! Btw, could you please tell me when the dateset is expected to be released? Thanks a lot!

Thanks. The release of competition training split will be released on June 9 and testing split will be released on June 13. More detailes please refer to our website. [MMVRAC ICCVW2021](https://sutdcv.github.io/multi-modal-video-reasoning/#/)

**Comment by Yarloy** [comment]
> > Can't wait for the release of the dataset! Btw, could you please tell me when the dateset is expected to be released? Thanks a lot!
> 
> Thanks. The competition training split will be released on June 9 and testing split will be released on June 13. More details please refer to our website. [MMVRAC ICCVW2021](https://sutdcv.github.io/multi-modal-video-reasoning/#/)

Thanks for your kindly reply! Can't wait to do research work on basis of this dataset lol
