### ISSUE TITLE
How to get download.sh ?

### ISSUE THREAD

**Issue by Note-Liu** [SUTDCV/UAV-Human#3]

**Comment by sayano-lee** [comment]
Hi, during the competition, the dataset is only accessible via our sharing link. The `download.sh` is temporarily removed and will be available when the competition is finished.

**Comment by Note-Liu** [comment]
> Hi, during the competition, the dataset is only accessible via our sharing link. The `download.sh` is temporarily removed and will be available when the competition is finished.

Thank you very much for your reply！
