### ISSUE TITLE
Will RGB videos be released for action recognition task?

### ISSUE THREAD

**Issue by zgzxy001** [SUTDCV/UAV-Human#6]
Hi, thank you for your great work! Will RGB videos be released for action recognition task? Currently I only see the fish-eye videos and skeleton in action recognition folder. Thanks!

**Comment by sayano-lee** [comment]
Hi, thanks for your patience. We've release rgb videos in our repo homepage and provided another new evaluation protocol. Please refer to the homepage for details. Thanks for your interest in our work.
