### ISSUE TITLE
How to convert files from your google drive to a video files? 

### ISSUE THREAD

**Issue by tomashlehmann** [SUTDCV/UAV-Human#7]
Hi, 
I downloaded files from your UAVHuman/ActionRecognition/RGBVideos directory but their format is weird. How to convert these files to a proper video files? Also where can I find labels to them and RGB-D videos?

**Comment by sayano-lee** [comment]
Hi @tomashlehmann, we checked the videos uploaded to the Google Drive and we were able to open it normally. Could you please describle your problem in details?

The filenames of the video samples contain the action labels. You can follow this to parse the action labels: `https://github.com/SUTDCV/UAV-Human/blob/master/uavhumanactiontools/uavhuman_rgb_dataset.py#L45`.

**Comment by tomashlehmann** [comment]
Downloaded files are named like f.e.: all_rgb.zip-004.008 - that's not the video extension and I cannot open it anyhow.

**Comment by sayano-lee** [comment]
Hi @tomashlehmann, you need to download all zip segments and extract from the first segment.
