### ISSUE TITLE
Action Labels

### ISSUE THREAD

**Issue by zgzxy001** [SUTDCV/UAV-Human#8]
Thank you for your great work!

Do you have the text of action labels, for example, class A001 denotes jumping. Thank you!

**Comment by jakefleisig** [comment]
I am also wondering how to get the action labels. could you please provide a text file?

**Comment by sayano-lee** [comment]
Hi @zgzxy001 @jakefleisig, thanks for your interests. We have updated the action classes. Please check the repo homepage.
