### ISSUE TITLE
Attribute files missing

### ISSUE THREAD

**Issue by snakeztc** [SUTDCV/UAV-Human#9]
When the attribute data will be provided in the Google Drive?

**Comment by sayano-lee** [comment]
Hi @snakeztc, we are updating the api for attribute data. The data will soon be released with the new API.

**Comment by snakeztc** [comment]
thanks. look forward to it.

**Comment by liuzhenyuzZ** [comment]
+1

**Comment by sayano-lee** [comment]
@snakeztc @liuzhenyuzZ Hi all, sorry for the delay and thanks for the patience. The attribute data and a simple code snippet have been uploaded. Please check.
